config/routes.rb
Refinery::Application.routes.draw do
  resources :news, :as => :news_items, :controller => :news_items, :only => [:show, :index]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :news, :except => :show, :as => :news_items, :controller => :news_items
  end
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  translates :title, :body, :external_url
  
  attr_accessor :locale # to hold temporarily

  alias_attribute :content, :body
  validates :title, :content, :publish_date, :presence => true

  has_friendly_id :title, :use_slug => true

  acts_as_indexed :fields => [:title, :body]

  default_scope :order => "publish_date DESC"

  # If you're using a named scope that includes a changing variable you need to wrap it in a lambda
  # This avoids the query being cached thus becoming unaffected by changes (i.e. Time.now is constant)
  scope :not_expired, lambda {
    news_items = Arel::Table.new(NewsItem.table_name)
    where(news_items[:expiration_date].eq(nil).or(news_items[:expiration_date].gt(Time.now)))
  }
  scope :published, lambda {
    not_expired.where("publish_date < ?", Time.now)
  }
  scope :latest, lambda { |*l_params|
    published.limit( l_params.first || 10)
  }

  # rejects any page that has not been translated to the current locale.
  scope :translated, lambda {
    pages = Arel::Table.new(NewsItem.table_name)
    translations = Arel::Table.new(NewsItem.translations_table_name)

    includes(:translations).where(
      translations[:locale].eq(Globalize.locale)).where(pages[:id].eq(translations[:news_item_id]))
  }

  def not_published? # has the published date not yet arrived?
    publish_date > Time.now
  end

  # for will_paginate
  def self.per_page
    20
  end

end

app/controllers/admin/news_items_controller.rb
class Admin::NewsItemsController < Admin::BaseController

  crudify :news_item, :order => "publish_date DESC"

end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  before_filter :find_page
  before_filter :find_published_news_items, :only => [:index]
  before_filter :find_news_item, :find_latest_news_items, :only => [:show]

  def index
    # render 'index'
  end

  def show
    # render 'show'
  end

protected

  def find_latest_news_items
    @news_items = NewsItem.latest.translated
  end

  def find_published_news_items
    @news_items = NewsItem.published.translated.paginate(:page => params[:page],
                                              :per_page => NewsItem.per_page)
  end

  def find_news_item
    @news_item = NewsItem.published.translated.find(params[:id])
  end

  def find_page
    @page = Page.find_by_link_url("/news")
  end

end

app/views/admin/news_items/_form.html.erb
<%= form_for [:admin, @news_item] do |f| %>
  <%= render :partial => "/shared/admin/error_messages",
             :locals => {
               :object => @news_item,
               :include_object_name => true
             } %>

  <%= render :partial => "locale_picker",
             :locals => {
               :current_locale => Thread.current[:globalize_locale]
             } if defined?(::Refinery::I18n) %>

  <div class='field'>
    <%= f.label :title %>
    <%= f.text_field :title, :class => "larger widest" %>
  </div>

  <div class='field'>
    <%= f.label :publish_date %>
    <%= f.datetime_select :publish_date %>
  </div>

  <div class='field'>
    <%= f.label :expiration_date %>
    <%= f.datetime_select :expiration_date, :start_year => Time.now.year,
                                            :include_blank => true %>
  </div>

  <div class='field'>
    <%= f.label :content %>
    <%= f.text_area :content, :rows => "20", :class => "wymeditor widest" %>
  </div>

  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => f,
               :continue_editing => true,
               :delete_title => t('admin.news_items.news_item.delete'),
               :delete_confirmation => t('shared.admin.delete.message', :title => @news_item.title)
             } %>

<% end %>

app/views/admin/news_items/_locale_picker.html.erb
<input type='hidden' name='switch_locale' id='switch_locale' value='<%= local_assigns[:current_locale] %>' />
<% if (locales ||= ::Refinery::I18n.frontend_locales).present? and locales.many? %>
  <ul id='switch_locale_picker' class='clearfix'>
    <% locales.each do |locale| %>
      <li<%= " class='selected'" if locale.to_s == local_assigns[:current_locale].to_s %>>
        <%= link_to refinery_icon_tag("flags/#{locale}.png", :size => '48x33'),
                    url_for(:switch_locale => locale) %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/admin/news_items/_news_item.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>'>
  <span class='title'>
    <%= news_item.title %>
    <span class="preview">
      <%= t('.published') %> <%= l(news_item.publish_date, :format => :short) %>
    </span>
    <% if defined?(::Refinery::I18n) and ::Refinery::I18n.frontend_locales.many? and
          (locales = news_item.translations.collect{|t| t.locale}).present? %>
      <span class='preview'>
        <% locales.each do |locale| %>
          <%= refinery_icon_tag "flags/#{locale}.png", :size => '16x11' %>
        <% end %>
      </span>
    <% end %>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag('application_go.png'), news_item_url(news_item),
                :title => t('.view_live_html'),
                :target => "_blank" %>
    <%= link_to refinery_icon_tag('application_edit.png'), edit_admin_news_item_path(news_item),
                :title => t('.edit') %>
    <%= link_to refinery_icon_tag('delete.png'), admin_news_item_path(news_item),
                :class => "cancel confirm-delete",
                :title => t('.delete'),
                :method => :delete,
                :confirm => t('shared.admin.delete.message', :title => news_item.title) %>
  </span>
</li>

app/views/admin/news_items/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/news_items/index.html.erb
<div id='actions'>
  <ul>
    <li>
      <%= render :partial => "/shared/admin/search", :locals => {:url => admin_news_items_url} %>
    </li>
    <li>
      <%= link_to t('.create'), new_admin_news_item_url, :class => "add_icon" %>
    </li>
  </ul>
</div>
<div id='records'>
  <% if searching? %>
    <h2><%= t('shared.admin.search.results_for', :query => params[:search]) %></h2>
  <% end %>
  <% if @news_items.any? %>
    <%= will_paginate @news_items %>
    <ul>
      <%= render :partial => "news_item", :collection => @news_items %>
    </ul>
    <%= will_paginate @news_items %>
  <% else %>
    <p>
      <% unless searching? %>
        <strong><%= t('.no_items_yet') %></strong>
      <% else %>
        <%= t('shared.admin.search.no_results') %>
      <% end %>
    </p>
  <% end %>
</div>

app/views/admin/news_items/new.html.erb
<%= render :partial => "form" %>

app/views/news_items/_recent_posts.html.erb
<nav id="recent_news_items">
  <h2><%= t('.recent_posts') %></h2>
  <ul>
    <% @news_items.each do |item| %>
      <li>
        <%= link_to item.title, news_item_url(item) %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/news_items/index.html.erb
<% content_for :body_content_left do %>
  <%=raw @page.content_for(Page.default_parts.first.to_sym) if @news_items.offset == 0 %>

  <% if @news_items.any? %>
    <% @news_items.each do |item| %>
      <article class="news_item_truncated">
        <h2><%= link_to item.title, news_item_url(item) %></h2>
        <p>
          <small><%= t('.published') %> <%= l(item.publish_date, :format => :long) %></small>
        </p>
        <%= truncate  item.body, :length => 200,
                      :omission => " ... #{link_to t('.read_more'), news_item_url(item)}",
                      :preserve_html_tags => true %>
      </article>
    <% end %>

    <%= will_paginate(@news_items) %>
  <% else %>
    <p><em><%= t('.no_items_yet') %></em></p>
  <% end %>
<% end -%>

<%= render :partial => "/shared/content_page" %>

app/views/news_items/show.html.erb
<% content_for :body_content_title, @news_item.title %>
<% content_for :body_content_left do %>
  <article class="news_item">
    <p>
      <small><%= t('.published') %> <%= l(@news_item.publish_date, :format => :long) %></small>
    </p>
    <%= @news_item.body.html_safe %>
    <p>
      <%= link_to t('.back_to_index'), news_items_url %>
    </p>
  </article>
<% end %>
<% content_for :body_content_right, render(:partial => 'recent_posts') %>

<%= render :partial => "/shared/content_page" %>